# Generated by Django 4.1.7 on 2023-02-28 10:21

from django.db import migrations, models
import movie_downloader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='m_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=191)),
                ('description', models.TextField(max_length=500, null=True)),
                ('tlink', models.TextField(max_length=500, null=True)),
                ('mlink', models.TextField(max_length=500)),
                ('category', models.TextField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=movie_downloader.models.filepath)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
