# Generated by Django 4.1.7 on 2023-02-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_downloader', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
